Refactor insecureUrl check into service
Rise-Vision/rise-vision-apps pull request #2031
Opened 2020-09-08 19:14 UTC by alex-deaconu

## Description
Refactor insecureUrl check into service

Update all refrences

[stage-15]

## Motivation and Context
Refactor in case we want to update logic at a later date.

## How Has This Been Tested?
Tested all 3 places manually. Updated unit tests.

## Release Plan:
- As the Submitter, upon requesting review of this pull request, I confirm that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed. 
- As the Reviewer, upon approving the changes in this PR, I confirm I have reviewed and I agree that the [Release Checklist](https://help.risevision.com/hc/en-us/articles/360031119991) has been completed

#### Release Checklist Items Skipped?
No

2020-09-08 19:15 UTC, alex-deaconu commented
@olegrise please review. Thanks!

2020-09-09 16:01 UTC, olegrise requested changes

2020-09-09 16:34 UTC, alex-deaconu commented
@olegrise fixed the issue in this PR, the `should should` problem from the other PR and cleaned up an invalid test. Please review the latest commit. Thanks!

2020-09-09 17:00 UTC, olegrise approved these changes
@alex-deaconu looks good. Thanks for fixing.

2020-09-09 17:12 UTC, merged